name = "OMC Minecraft Modpack"
author = "lodi21"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1ab9515c800646c1a56a1147bda396d700daf14724d79ecd4662e717f6e1fd3b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.209"
