name = "OMC Minecraft Modpack"
author = "lodi21"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6cb4cfcecfd94e6c624cef770ec6f5ff857014a210e2febd1d708d94813ff61d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.209"
