name = "OMC Minecraft Modpack"
author = "lodi21"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ff4f14054b65afed5ad10a7f9a446fac5cb2d23fbff0fd0537b007e98043ca3c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.209"
