name = "오만추 모드팩"
author = "CheshireOverLap"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f84df7cd0bec55a2f480464589e83657a5243d96ab28a7dff27e1a792fb7ee8b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.209"
