name = "오만추 모드팩"
author = "CheshireOverLap"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "75c32f261a37d6eed842c9a69d8f26500aad7a1092a5a0a30322081dcd47900e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.209"
