name = "오만추 모드팩"
author = "CheshireOverLap"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "afd925aa19816675f8653440d7e7cafdc7ebeb313c5e84c6d6ccadfe77dc960b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.209"
