name = "오만추 모드팩"
author = "CheshireOverLap"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2abc6ed7062079db50269b4a5ab126723ccb8c930cec0b5d58b39962be2b196b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.209"
