name = "OMC Minecraft Modpack"
author = "lodi21"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d9561e30f865863abb0ffbee73f5e4845c54db6bdbad64cf8ad53081eb640482"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.209"
