name = "OMC Minecraft Modpack"
author = "lodi21"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "57d4185475573b65f26990485a7c5872e0686d8c7aeddfaf6b595082a5d98532"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.209"
