name = "오만추 모드팩"
author = "CheshireOverLap"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "30ddceb121a4cd841f386973e0045a47271ed7dd3b90b26888c838d73263d94b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.209"
